services:
    webui:
        container_name: restaurant-booking-system-webui
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        networks:
            - reservation_backend
        ports:
            - "3000:80"

networks:
    reservation_backend:
        external: true
